/**
 * Mapping of German Pokémon names to English names.
 * Keys are lowercase German names for case-insensitive lookup.
 * Only contains entries where the German name differs from the English name.
 */
export const DE_TO_EN: Record<string, string> = {
  // ── Gen 1 ────────────────────────────────────────────────────────────────
  bisasam: 'Bulbasaur',
  bisaknosp: 'Ivysaur',
  bisaflor: 'Venusaur',
  glumanda: 'Charmander',
  glutexo: 'Charmeleon',
  glurak: 'Charizard',
  schiggy: 'Squirtle',
  schillok: 'Wartortle',
  turtok: 'Blastoise',
  raupy: 'Caterpie',
  safrakling: 'Metapod',
  smettbo: 'Butterfree',
  hornliu: 'Weedle',
  kokuna: 'Kakuna',
  bibor: 'Beedrill',
  taubsi: 'Pidgey',
  tauboga: 'Pidgeotto',
  tauboss: 'Pidgeot',
  rattfratz: 'Rattata',
  rattikarl: 'Raticate',
  habitak: 'Spearow',
  ibitak: 'Fearow',
  rettan: 'Ekans',
  sandan: 'Sandshrew',
  sandamer: 'Sandslash',
  piepi: 'Clefairy',
  pixi: 'Clefable',
  vulnona: 'Ninetales',
  pummeluff: 'Jigglypuff',
  knuddeluff: 'Wigglytuff',
  myrapla: 'Oddish',
  duflor: 'Gloom',
  giflor: 'Vileplume',
  parasek: 'Parasect',
  bluzuk: 'Venonat',
  omot: 'Venomoth',
  digda: 'Diglett',
  digdri: 'Dugtrio',
  mauzi: 'Meowth',
  snobilikat: 'Persian',
  enton: 'Psyduck',
  menki: 'Mankey',
  rasaff: 'Primeape',
  fukano: 'Growlithe',
  arkani: 'Arcanine',
  quapsel: 'Poliwag',
  quaputzi: 'Poliwhirl',
  quappo: 'Poliwrath',
  simsala: 'Alakazam',
  machollo: 'Machop',
  maschock: 'Machoke',
  machomei: 'Machamp',
  knofensa: 'Bellsprout',
  ultrigaria: 'Weepinbell',
  sarplaff: 'Victreebel',
  tentacha: 'Tentacool',
  tentoxa: 'Tentacruel',
  kleinstein: 'Geodude',
  georok: 'Graveler',
  geowaz: 'Golem',
  ponita: 'Ponyta',
  gallopa: 'Rapidash',
  flegmon: 'Slowpoke',
  lahmus: 'Slowbro',
  magnetilo: 'Magnemite',
  porenta: "Farfetch'd",
  dodu: 'Doduo',
  dodri: 'Dodrio',
  jurob: 'Seel',
  jugong: 'Dewgong',
  sleima: 'Grimer',
  sleimok: 'Muk',
  muschas: 'Shellder',
  austos: 'Cloyster',
  nebulak: 'Gastly',
  alpollo: 'Haunter',
  traumato: 'Drowzee',
  voltobal: 'Voltorb',
  lektrobal: 'Electrode',
  owei: 'Exeggcute',
  kokowei: 'Exeggutor',
  tragosso: 'Cubone',
  knogga: 'Marowak',
  kicklee: 'Hitmonlee',
  nockchan: 'Hitmonchan',
  schlurp: 'Lickitung',
  smogon: 'Koffing',
  smogmog: 'Weezing',
  rihorn: 'Rhyhorn',
  rizeros: 'Rhydon',
  chaneira: 'Chansey',
  kangama: 'Kangaskhan',
  seeper: 'Horsea',
  seemon: 'Seadra',
  goldini: 'Goldeen',
  golking: 'Seaking',
  sterndu: 'Staryu',
  pantimos: 'Mr. Mime',
  sichlor: 'Scyther',
  rossana: 'Jynx',
  elektek: 'Electabuzz',
  karpador: 'Magikarp',
  garados: 'Gyarados',
  evoli: 'Eevee',
  aquana: 'Vaporeon',
  blitza: 'Jolteon',
  flamara: 'Flareon',
  amonitas: 'Omanyte',
  amoroso: 'Omastar',
  relaxo: 'Snorlax',
  arktos: 'Articuno',
  lavados: 'Moltres',
  dragonir: 'Dragonair',
  dragoran: 'Dragonite',
  mewtu: 'Mewtwo',

  // ── Gen 2 ────────────────────────────────────────────────────────────────
  endivie: 'Chikorita',
  lorblatt: 'Bayleef',
  meganie: 'Meganium',
  feurigel: 'Cyndaquil',
  igelavar: 'Quilava',
  tornupto: 'Typhlosion',
  karnimani: 'Totodile',
  tyracroc: 'Croconaw',
  impergator: 'Feraligatr',
  wiesor: 'Sentret',
  wiesenior: 'Furret',
  noctuh: 'Noctowl',
  webarak: 'Spinarak',
  iksbat: 'Crobat',
  lampi: 'Chinchou',
  pii: 'Cleffa',
  fluffeluff: 'Igglybuff',
  voltilamm: 'Mareep',
  lamepert: 'Flaaffy',
  mogelbaum: 'Sudowoodo',
  quaxo: 'Politoed',
  hoppspross: 'Hoppip',
  hubelupf: 'Skiploom',
  papungha: 'Jumpluff',
  griffel: 'Aipom',
  sonnkern: 'Sunkern',
  sonnflora: 'Sunflora',
  wupper: 'Wooper',
  morlord: 'Quagsire',
  psiana: 'Espeon',
  nachtara: 'Umbreon',
  kramurx: 'Murkrow',
  laschoking: 'Slowking',
  traunfugil: 'Misdreavus',
  icognito: 'Unown',
  woingenau: 'Wobbuffet',
  tannza: 'Pineco',
  forstellka: 'Forretress',
  dummisel: 'Dunsparce',
  skorgla: 'Gligar',
  stahlos: 'Steelix',
  baldorfish: 'Qwilfish',
  scherox: 'Scizor',
  pottrott: 'Shuckle',
  skaraborn: 'Heracross',
  zangoss: 'Sneasel',
  schneckmag: 'Slugma',
  quiekel: 'Swinub',
  keifel: 'Piloswine',
  corasonn: 'Corsola',
  mantax: 'Mantine',
  panzaeron: 'Skarmory',
  hunduster: 'Houndour',
  hundemon: 'Houndoom',
  damhirplex: 'Stantler',
  farbeagle: 'Smeargle',
  rabauz: 'Tyrogue',
  kapoera: 'Hitmontop',
  kussilla: 'Smoochum',
  blissey: 'Blissey',
  togekiss: 'Togekiss',

  // ── Gen 3 ────────────────────────────────────────────────────────────────
  geckarbor: 'Treecko',
  reptain: 'Grovyle',
  gewaldro: 'Sceptile',
  flemmli: 'Torchic',
  jungglut: 'Combusken',
  lohgock: 'Blaziken',
  hydropi: 'Mudkip',
  moorabbel: 'Marshtomp',
  sumpex: 'Swampert',
  zirpmon: 'Wurmple',
  schaloko: 'Silcoon',
  papinella: 'Beautifly',
  ninjatom: 'Shedinja',
  makuhita: 'Makuhita',
  hariyama: 'Hariyama',
  azurill: 'Azurill',
  schneppke: 'Wingull',
  guardevoir: 'Gardevoir',
  kirliz: 'Kirlia',
  wasabi: 'Sableye',
  meditie: 'Meditite',
  medicham: 'Medicham',
  roselia: 'Roselia',
  pflanzigel: 'Cacnea',
  noktuska: 'Cacturne',
  spoink: 'Spoink',
  groink: 'Grumpig',
  libelldra: 'Flygon',
  lunastein: 'Lunatone',
  sonnfel: 'Solrock',
  barschwa: 'Barboach',
  welsar: 'Whiscash',
  krebscorps: 'Crawdaunt',
  feebas: 'Feebas',
  castform: 'Castform',
  tropius: 'Tropius',
  snibunna: 'Absol',

  // ── Gen 4 ────────────────────────────────────────────────────────────────
  chelast: 'Turtwig',
  chelcarain: 'Grotle',
  chelterrar: 'Torterra',
  panflam: 'Chimchar',
  panpyro: 'Monferno',
  panferno: 'Infernape',
  plinfa: 'Piplup',
  pliprin: 'Prinplup',
  impoleon: 'Empoleon',
  staralili: 'Starly',
  bibanel: 'Bibarel',
  sheinux: 'Shinx',
  luxio: 'Luxio',
  luxtra: 'Luxray',
  knospi: 'Budew',
  roserade: 'Roserade',
  koknodon: 'Cranidos',
  rameidon: 'Rampardos',
  shieldon: 'Shieldon',
  bastiodon: 'Bastiodon',
  burmy: 'Burmy',
  burmadame: 'Wormadam',
  mottomot: 'Mothim',
  combee: 'Combee',
  honchkrow: 'Honchkrow',
  glibunkel: 'Glameow',
  purrlon: 'Purugly',
  bronzel: 'Bronzor',
  bronzong: 'Bronzong',
  kopieff: 'Chatot',
  wonneira: 'Happiny',
  gastrodon: 'Gastrodon',
  ambipom: 'Ambipom',
  drifzepeli: 'Drifloon',
  driflon: 'Drifblim',
  haspiror: 'Buneary',
  schlapor: 'Lopunny',
  mismagius: 'Mismagius',
  riolu: 'Riolu',
  lucario: 'Lucario',
  hippopotas: 'Hippopotas',
  hippowdon: 'Hippowdon',
  skorupi: 'Skorupi',
  drapion: 'Drapion',
  kaumalat: 'Croagunk',
  toxiquak: 'Toxicroak',
  weavile: 'Weavile',
  magnezone: 'Magnezone',
  lickitak: 'Lickilicky',
  rihornior: 'Rhyperior',
  tangoloss: 'Tangrowth',
  elevoltek: 'Electivire',
  magbrant: 'Magmortar',
  yanmega: 'Yanmega',
  lebellos: 'Leafeon',
  glaziola: 'Glaceon',
  mamutel: 'Mamoswine',
  'porygon-z': 'Porygon-Z',
  simsalage: 'Gallade',
  dusknosp: 'Dusknoir',
  shnebedeck: 'Froslass',

  // ── Gen 5 ────────────────────────────────────────────────────────────────
  vegichita: 'Snivy',
  serpifeu: 'Servine',
  serpiroyal: 'Serperior',
  floink: 'Tepig',
  ferkokel: 'Pignite',
  flambirex: 'Emboar',
  ottaro: 'Oshawott',
  devol: 'Dewott',
  admurai: 'Samurott',
  patrat: 'Patrat',
  kibango: 'Lillipup',
  herdier: 'Herdier',
  bisafank: 'Stoutland',
  felino: 'Purrloin',
  bissamba: 'Liepard',
  peppeck: 'Pansage',
  simmance: 'Simisage',
  flamiau: 'Pansear',
  veralto: 'Simisear',
  pandir: 'Panpour',
  frograktor: 'Pidove',
  zebritz: 'Zebstrika',
  grobiax: 'Boldore',
  gigantes: 'Gigalith',
  sopowick: 'Audino',
  gufa: 'Timburr',
  kongol: 'Conkeldurr',
  quabbel: 'Tympole',
  lipplosion: 'Palpitoad',
  maslapex: 'Seismitoad',
  throrian: 'Throh',
  schlarek: 'Sawk',
  strawick: 'Sewaddle',
  trombork: 'Swadloon',
  leavanny: 'Leavanny',
  sentaround: 'Venipede',
  rotomurf: 'Scolipede',
  cotobulon: 'Cottonee',
  elfun: 'Whimsicott',
  sesokitz: 'Petilil',
  samolz: 'Lilligant',
  krookodil: 'Krookodile',
  marachamba: 'Maractus',
  grenjalk: 'Dwebble',
  castellith: 'Crustle',
  schlingel: 'Scraggy',
  schlunz: 'Scrafty',
  nekroneka: 'Yamask',
  ruineras: 'Cofagrigus',
  skunkapuh: 'Trubbish',
  garbodor: 'Garbodor',
  zorua: 'Zorua',
  zoroark: 'Zoroark',
  minccino: 'Minccino',
  cinccino: 'Cinccino',
  emolga: 'Emolga',
  karabrust: 'Karrablast',
  escavalier: 'Escavalier',
  galvantula: 'Galvantula',
  ferroseed: 'Ferroseed',
  ferrothorn: 'Ferrothorn',
  monozykling: 'Klink',
  duozykling: 'Klang',
  triozykling: 'Klinklang',
  elezeba: 'Elgyem',
  laternecto: 'Litwick',
  lachelier: 'Lampent',
  lampentar: 'Chandelure',
  bannipoto: 'Vanillite',
  banirbis: 'Vanillish',
  banistar: 'Vanilluxe',
  axew: 'Axew',
  schildax: 'Fraxure',
  maxax: 'Haxorus',
  cryrak: 'Cubchoo',
  waschuft: 'Mienshao',
  golett: 'Golett',
  golurk: 'Golurk',
  pawniard: 'Pawniard',
  bisharp: 'Bisharp',
  heatmor: 'Heatmor',
  durant: 'Durant',
  zweronz: 'Zweilous',
  ordragon: 'Hydreigon',
  larvesta: 'Larvesta',
  vocarona: 'Volcarona',
  kobalium: 'Cobalion',
  terrakium: 'Terrakion',
  viridium: 'Virizion',
  reshiram: 'Reshiram',
  zekrom: 'Zekrom',
  kyurem: 'Kyurem',
  keldeo: 'Keldeo',
  meloetta: 'Meloetta',
  genesect: 'Genesect',

  // ── Gen 6 ────────────────────────────────────────────────────────────────
  igamaro: 'Chespin',
  igastarnish: 'Chesnaught',
  fynx: 'Fennekin',
  fiaro: 'Delphox',
  froxy: 'Froakie',
  quajutsu: 'Greninja',
  litleo: 'Litleo',
  pyroleo: 'Pyroar',
  skiddo: 'Skiddo',
  gommelka: 'Gogoat',
  pankekku: 'Pancham',
  borderlo: 'Pangoro',
  espurr: 'Espurr',
  meowstic: 'Meowstic',
  inkay: 'Inkay',
  malamar: 'Malamar',
  clauncher: 'Clauncher',
  clawitzer: 'Clawitzer',
  helioptile: 'Helioptile',
  heliolisk: 'Heliolisk',
  sylveon: 'Sylveon',
  hawlucha: 'Hawlucha',
  dedenne: 'Dedenne',
  goomy: 'Goomy',
  goodra: 'Goodra',
  klefki: 'Klefki',
  phantump: 'Phantump',
  trevenant: 'Trevenant',
  noibat: 'Noibat',
  noivern: 'Noivern',
  xerneas: 'Xerneas',
  yveltal: 'Yveltal',
  zygarde: 'Zygarde',
  diancie: 'Diancie',
  hoopa: 'Hoopa',
  volcanion: 'Volcanion',

  // ── Gen 7 ────────────────────────────────────────────────────────────────
  bauz: 'Rowlet',
  arboretoss: 'Dartrix',
  silvarro: 'Decidueye',
  fuegro: 'Incineroar',
  robball: 'Popplio',
  syren: 'Primarina',
  yungoos: 'Yungoos',
  gumshoos: 'Gumshoos',
  grubbin: 'Grubbin',
  charjabug: 'Charjabug',
  vikavolt: 'Vikavolt',
  cutiefly: 'Cutiefly',
  ribombee: 'Ribombee',
  rockruff: 'Rockruff',
  wolwerock: 'Lycanroc',
  wimpod: 'Wimpod',
  golisopod: 'Golisopod',
  mimikyu: 'Mimikyu',
  komala: 'Komala',
  turtonator: 'Turtonator',
  togedemaru: 'Togedemaru',
  nihilego: 'Nihilego',
  buzzwole: 'Buzzwole',
  pheromosa: 'Pheromosa',
  xurkitree: 'Xurkitree',
  celesteela: 'Celesteela',
  kartana: 'Kartana',
  guzzlord: 'Guzzlord',
  necrozma: 'Necrozma',
  magearna: 'Magearna',
  marshadow: 'Marshadow',
  poipole: 'Poipole',
  naganadel: 'Naganadel',
  stakataka: 'Stakataka',
  blacephalon: 'Blacephalon',
  zeraora: 'Zeraora',
  meltan: 'Meltan',
  melmetal: 'Melmetal',

  // ── Gen 8 ────────────────────────────────────────────────────────────────
  kuschelaff: 'Grookey',
  thwackey: 'Thwackey',
  rillaboom: 'Rillaboom',
  hopplo: 'Scorbunny',
  laufenten: 'Raboot',
  liberlo: 'Cinderace',
  memmeon: 'Sobble',
  intelleon: 'Intelleon',
  wolly: 'Wooloo',
  dubwool: 'Dubwool',
  skwovet: 'Skwovet',
  greedent: 'Greedent',
  rookidee: 'Rookidee',
  corvisquire: 'Corvisquire',
  corviknight: 'Corviknight',
  gossifleur: 'Gossifleur',
  eldegoss: 'Eldegoss',
  yamper: 'Yamper',
  boltund: 'Boltund',
  rolycoly: 'Rolycoly',
  carkol: 'Carkol',
  coalossal: 'Coalossal',
  applin: 'Applin',
  flapple: 'Flapple',
  appletun: 'Appletun',
  sandaconda: 'Sandaconda',
  cramorant: 'Cramorant',
  toxel: 'Toxel',
  toxtricity: 'Toxtricity',
  centiskorch: 'Centiskorch',
  clobbopus: 'Clobbopus',
  grapploct: 'Grapploct',
  sinistea: 'Sinistea',
  polteageist: 'Polteageist',
  hatterene: 'Hatterene',
  grimmsnarl: 'Grimmsnarl',
  obstagoon: 'Obstagoon',
  perrserker: 'Perrserker',
  cursola: 'Cursola',
  'sirfetch\'d': "Sirfetch'd",
  sirfetchd: "Sirfetch'd",
  milcery: 'Milcery',
  alcremie: 'Alcremie',
  falinks: 'Falinks',
  frosmoth: 'Frosmoth',
  morpeko: 'Morpeko',
  cufant: 'Cufant',
  copperajah: 'Copperajah',
  dracozolt: 'Dracozolt',
  dracovish: 'Dracovish',
  duraludon: 'Duraludon',
  dreepy: 'Dreepy',
  drakloak: 'Drakloak',
  dragapult: 'Dragapult',
  zacian: 'Zacian',
  zamazenta: 'Zamazenta',
  eternatus: 'Eternatus',
  kubfu: 'Kubfu',
  urshifu: 'Urshifu',
  zarude: 'Zarude',
  regieleki: 'Regieleki',
  regidrago: 'Regidrago',
  calyrex: 'Calyrex',

  // ── Gen 9 ────────────────────────────────────────────────────────────────
  felori: 'Sprigatito',
  floragato: 'Floragato',
  meowscarada: 'Meowscarada',
  krokel: 'Fuecoco',
  crocalor: 'Crocalor',
  skeledirge: 'Skeledirge',
  kwaks: 'Quaxly',
  kwaksel: 'Quaxwell',
  quaquaval: 'Quaquaval',
  lechonk: 'Lechonk',
  oinkologne: 'Oinkologne',
  pawmi: 'Pawmi',
  pawmo: 'Pawmo',
  pawmot: 'Pawmot',
  fidough: 'Fidough',
  dachsbun: 'Dachsbun',
  smoliv: 'Smoliv',
  dolliv: 'Dolliv',
  arboliva: 'Arboliva',
  nacli: 'Nacli',
  naclstack: 'Naclstack',
  garganacl: 'Garganacl',
  charcadet: 'Charcadet',
  armarouge: 'Armarouge',
  ceruledge: 'Ceruledge',
  bellibolt: 'Bellibolt',
  mabosstiff: 'Mabosstiff',
  grafaiai: 'Grafaiai',
  klawf: 'Klawf',
  espathra: 'Espathra',
  tinkatink: 'Tinkatink',
  tinkatuff: 'Tinkatuff',
  tinkaton: 'Tinkaton',
  palafin: 'Palafin',
  revavroom: 'Revavroom',
  orthworm: 'Orthworm',
  glimmora: 'Glimmora',
  houndstone: 'Houndstone',
  cetitan: 'Cetitan',
  dondozo: 'Dondozo',
  tatsugiri: 'Tatsugiri',
  annihilape: 'Annihilape',
  clodsire: 'Clodsire',
  farigiraf: 'Farigiraf',
  dudunsparce: 'Dudunsparce',
  kingambit: 'Kingambit',
  baxcalibur: 'Baxcalibur',
  gholdengo: 'Gholdengo',
  koraidon: 'Koraidon',
  miraidon: 'Miraidon',
  dipplin: 'Dipplin',
  ogerpon: 'Ogerpon',
  archaludon: 'Archaludon',
  hydrapple: 'Hydrapple',
  terapagos: 'Terapagos',
  pecharunt: 'Pecharunt',
};

/**
 * Translates a German Pokémon name (or a name containing a German Pokémon name)
 * to the corresponding English name. Returns the translated string if a German
 * name was found, or null if no translation is available.
 *
 * Examples:
 *   translateGermanName('Glurak')      → 'Charizard'
 *   translateGermanName('Glurak EX')   → 'Charizard EX'
 *   translateGermanName('Bisasam V')   → 'Bulbasaur V'
 *   translateGermanName('Charizard')   → null  (already English)
 *   translateGermanName('mewtu')       → 'Mewtwo'
 */
export function translateGermanName(query: string): string | null {
  const trimmed = query.trim();
  if (!trimmed) return null;

  // Try full query first (handles names with spaces like "Mr. Mime")
  const fullLower = trimmed.toLowerCase();
  if (DE_TO_EN[fullLower]) return DE_TO_EN[fullLower]!;

  // Split and try first token, preserving any suffix (EX, GX, V, VMAX …)
  const tokens = trimmed.split(/\s+/);
  if (tokens.length === 0) return null;

  const firstName = tokens[0]!;
  const firstLower = firstName.toLowerCase();

  if (DE_TO_EN[firstLower]) {
    const englishName = DE_TO_EN[firstLower]!;
    const rest = tokens.slice(1).join(' ');
    return rest ? `${englishName} ${rest}` : englishName;
  }

  // Try first two tokens (e.g. "Mr Mime" written without a dot)
  if (tokens.length >= 2) {
    const twoTokensLower = `${tokens[0]} ${tokens[1]}`.toLowerCase();
    if (DE_TO_EN[twoTokensLower]) {
      const englishName = DE_TO_EN[twoTokensLower]!;
      const rest = tokens.slice(2).join(' ');
      return rest ? `${englishName} ${rest}` : englishName;
    }
  }

  return null;
}
